---
title: "Plotly FlexDashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
data("instacart")
instacart
```

Column {data-width=650}
-----------------------------------------------------------------------

### Plot 1: Top Ten Order Count by Department

```{r, warning=FALSE}
department=
  instacart %>% 
  count(department) %>% 
  mutate(department = fct_reorder(department, n)) %>%  
  top_n(10) %>% 
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar")
department
```

Column {data-width=350}
-----------------------------------------------------------------------

### Plot 2: Distribution of Days since prior order

```{r, warning=FALSE}
order_times=
  instacart %>% 
  count(days_since_prior_order, sort = TRUE) %>% 
  plot_ly(x = ~days_since_prior_order, y = ~n,  type = "scatter", mode = "markers", color = "pink", alpha = 0.5)
order_times
```

### Plot 3: Distribution of time products ordered from 3 departments

```{r}
plot_3=
  instacart %>% 
  filter(department == "pantry" | 
         department == "household" |
         department == "snacks") %>%
  plot_ly(x = ~department, y = ~order_hour_of_day, color = "department", type = "violin", colors = "purple")
plot_3
```

